<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rswnrw_carousel"
 *
 * Auto generated by Extension Builder 2017-01-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Homepage Carousel',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Seenu Gudipati',
    'author_email' => 'sg@afm-koeln.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.0.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
